# Generated by Django 3.2.12 on 2023-10-22 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessmodel',
            unique_together={('user', 'product')},
        ),
    ]
