# Generated by Django 3.2.12 on 2023-10-22 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_accessmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='урок')),
                ('video_link', models.URLField(unique=True, verbose_name='ссылка на видео')),
                ('duration', models.IntegerField(verbose_name='продолжительность')),
                ('product', models.ManyToManyField(related_name='lessons', to='product.Product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='ViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_view', models.IntegerField(default=0, verbose_name='просмотренно')),
                ('start_view', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='дата последнего просмотра')),
                ('status', models.CharField(default='Не просмотренно', max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewmodels', to='lesson.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewmodels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'модель просмотра',
                'verbose_name_plural': 'модели просмотра',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
